export const APP_LOADED = 'APP_LOADED';

export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const CLEAR_FORM = 'CLEAR_FORM';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const ORDER_LIST_FETCH = 'ORDER_LIST_FETCH';
export const ORDER_LIST_UNLOAD = 'ORDER_LIST_UNLOAD';
export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_GET = 'ORDER_GET';
export const ORDER_UNLOAD = 'ORDER_UNLOAD';

export const ORDER_CONTRACTOR_LIST_FETCH = 'ORDER_CONTRACTOR_LIST_FETCH';
export const ORDER_CONTRACTOR_LIST_UNLOAD = 'ORDER_CONTRACTOR_LIST_UNLOAD';
export const ORDER_CUSTOMER_LIST_FETCH = 'ORDER_CUSTOMER_LIST_FETCH';
export const ORDER_CUSTOMER_LIST_UNLOAD = 'ORDER_CUSTOMER_LIST_UNLOAD';

export const ORDER_TAG_ADD = 'ORDER_TAG_ADD';
export const ORDER_TAG_REMOVE = 'ORDER_TAG_REMOVE';

export const TAG_CREATE = 'TAG_CREATE';

export const TAGS_SUGGESTIONS_FETCH = 'TAGS_SUGGESTIONS_FETCH';
export const TAGS_SUGGESTIONS_CLEAR = 'TAGS_SUGGESTIONS_CLEAR';
export const TAG_SUGGESTION_SELECTED = 'TAG_SUGGESTION_SELECTED';

export const APPLY = 'APPLY';
export const APPLY_SUCCESS = 'APPLY_SUCCESS';
export const APPLICATION_CANCEL = 'APPLICATION_CANCEL';
export const APPLICATION_ACCEPT = 'APPLICATION_ACCEPT';
export const APPLICATION_DECLINE = 'APPLICATION_DECLINE';

export const CATEGORIES_FETCH = 'CATEGORIES_FETCH';
export const CATEGORIES_UNLOAD = 'CATEGORIES_UNLOAD';
export const CATEGORY_SELECT_TOGGLE = 'CATEGORY_SELECT_TOGGLE';
export const CATEGORY_COLLAPSE_TOGGLE = 'CATEGORY_COLLAPSE_TOGGLE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
