export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const APP_LOADED = 'APP_LOADED';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const CLEAR_FORM = 'CLEAR_FORM';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const ORDER_LIST_FETCH = 'ORDER_LIST_FETCH';
export const ORDER_LIST_UNLOAD = 'ORDER_LIST_UNLOAD';
export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_GET = 'ORDER_GET';
export const ORDER_UNLOAD = 'ORDER_UNLOAD';

export const ORDER_CONTRACTOR_LIST_FETCH = 'ORDER_CONTRACTOR_LIST_FETCH';
export const ORDER_CONTRACTOR_LIST_UNLOAD = 'ORDER_CONTRACTOR_LIST_UNLOAD';
export const ORDER_CUSTOMER_LIST_FETCH = 'ORDER_CUSTOMER_LIST_FETCH';
export const ORDER_CUSTOMER_LIST_UNLOAD = 'ORDER_CUSTOMER_LIST_UNLOAD';

export const ORDER_FILTER_UPDATE = 'ORDER_FILTER_UPDATE';
export const ORDER_FILTER_PROCESSED = 'ORDER_FILTER_PROCESSED';
export const ORDER_FILTER_RESET = 'ORDER_FILTER_RESET';

export const ORDER_CHAT_FETCH = 'ORDER_CHAT_FETCH';
export const ORDER_CHAT_SEND_MESSAGE = 'ORDER_CHAT_SEND_MESSAGE';
export const ORDER_CHAT_UNLOAD = 'ORDER_CHAT_UNLOAD';
export const ORDER_CHAT_ALLOW_ACCESS = 'ORDER_CHAT_ALLOW_ACCESS';
export const ORDER_CHAT_NEW_MESSAGE_RECEIVED = 'ORDER_CHAT_NEW_MESSAGE_RECEIVED';
export const ORDER_CHAT_MARK_AS_READ_IF_ANY = 'ORDER_CHAT_MARK_AS_READ_IF_ANY';

export const ORDER_TAG_ADD = 'ORDER_TAG_ADD';
export const ORDER_TAG_REMOVE = 'ORDER_TAG_REMOVE';

export const TAG_CREATE = 'TAG_CREATE';
export const TAG_SELECT = 'TAG_SELECT';

export const TAGS_SUGGESTIONS_FETCH = 'TAGS_SUGGESTIONS_FETCH';
export const TAGS_SUGGESTIONS_CLEAR = 'TAGS_SUGGESTIONS_CLEAR';
export const TAG_SUGGESTION_SELECTED = 'TAG_SUGGESTION_SELECTED';

export const APPLY = 'APPLY';
export const APPLY_SUCCESS = 'APPLY_SUCCESS';
export const APPLICATION_CANCEL = 'APPLICATION_CANCEL';
export const APPLICATION_ACCEPT = 'APPLICATION_ACCEPT';
export const APPLICATION_DECLINE = 'APPLICATION_DECLINE';

export const CATEGORIES_FETCH = 'CATEGORIES_FETCH';
export const CATEGORIES_UNLOAD = 'CATEGORIES_UNLOAD';
export const CATEGORIES_PRESELECT = 'CATEGORIES_PRESELECT';
export const CATEGORIES_SELECTED_RESET = 'CATEGORIES_SELECTED_RESET';
export const CATEGORY_SELECT_TOGGLE = 'CATEGORY_SELECT_TOGGLE';
export const CATEGORY_COLLAPSE_TOGGLE = 'CATEGORY_COLLAPSE_TOGGLE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET_DISCONNECT';
export const WEBSOCKET_ATTACH_LISTENER = 'WEBSOCKET_ATTACH_LISTENER';
export const WEBSOCKET_EMIT_EVENT = 'WEBSOCKET_EMIT_EVENT';

export const USER_NOTIFICATIONS_LOAD = 'USER_NOTIFICATIONS_LOAD';
export const USER_NOTIFICATIONS_UNLOAD = 'USER_NOTIFICATIONS_UNLOAD';
export const USER_NOTIFICATIONS_SAVE = 'USER_NOTIFICATIONS_UPDATE';
export const USER_NOTIFICATIONS_UPDATE_CATEGORIES = 'USER_NOTIFICATIONS_UPDATE_CATEGORIES';

export const READ_NOTIFICATIONS = 'READ_NOTIFICATIONS';
