export const ORDER_APPLICATION_STATUS_NEW = 0;
export const ORDER_APPLICATION_STATUS_ACCEPTED = 1;
export const ORDER_APPLICATION_STATUS_DECLINED = 2;
export const ORDER_APPLICATION_STATUS_WITHDRAWN = 3;
