export const ORDER_CHAT_NEW_MESSAGE = 'ORDER_CHAT_NEW_MESSAGE';
export const ORDER_APPLICATION_APPROVED = 'ORDER_APPLICATION_APPROVED';
export const ORDER_APPLICATION_DECLINED = 'ORDER_APPLICATION_DECLINED';
export const ORDER_APPLICATION_REQUEST_RECEIVED = 'ORDER_APPLICATION_REQUEST_RECEIVED';

export const NEW_UNREAD_NOTIFICATIONS = 'NEW_UNREAD_NOTIFICATIONS';
